FROM python:3.11.4-alpine

COPY requirements.txt /bot/
WORKDIR /bot

RUN apk add --no-cache --virtual deps gcc musl-dev libffi-dev g++ git && \
  pip install pip --no-cache-dir --upgrade && \
  pip install setuptools wheel --no-cache-dir --upgrade && \
  MAKEFLAGS="-j $(nproc)" pip install -r requirements.txt --upgrade

COPY *.py /bot/
COPY *.env /bot/

ADD data /bot/data
ADD cogs /bot/cogs

ENTRYPOINT ["python", "bot.py"]