version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: omnitron-bot
    volumes:
      - ./logs:/bot/logs
      - ./temp:/bot/temp
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=DEVELOPMENT
    restart: always
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:64d4f12-alpine
    container_name: lavalink
    restart: always
    volumes:
      - ./lavalink:/opt/Lavalink
