version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: omnitron-bot
    volumes:
      - ./logs:/bot/logs
      - ./temp:/bot/temp
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - lavalink

  lavalink:
    build: lavalink
    container_name: lavalink
    volumes:
      - ./lavalink/logs:/opt/Lavalink/logs
      - ./lavalink/logs/hs_err_pid1.log:/opt/Lavalink/hs_err_pid1.log
